language: EN
strict: false
output:
  file_path: fluidattacks-results.sarif
  format: SARIF
ss:
  include:
    - .
  exclude:
    - environment/backend/
sca:
  include:
    - .
dast:
  urls:
    - url: https://www.fluidattacks.com