language: EN
strictness_threshold: critical
output:
  file_path: fluidattacks-results.sarif
  format: SARIF
ss:
  include:
    - .
  exclude:
    - environment/backend/
sca:
  include:
    - .
sast:
  include:
    - .
dast:
  urls:
    - url: https://www.google.com