# Test workflow for machine
name: Security Scans
on:
  push:

jobs:
  sast:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: fluidattacks/sast-action@1.2.0
        id: scan
        with:
          scanner_mode: full

      - name: Upload results to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: ${{ steps.scan.outputs.sarif_file }}

      - name: Fail if vulnerabilities found
        if: steps.scan.outputs.vulnerabilities_found == 'true'
        run: exit 1

  sca-scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4

      - uses: fluidattacks/sca-action@1.1.0
        id: scan
        with:
          scanner_mode: full

      - name: Upload results to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: ${{ steps.scan.outputs.sarif_file }}

      - name: Fail if vulnerabilities found
        if: steps.scan.outputs.vulnerabilities_found == 'true'
        run: exit 1

  dast-scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4

      - uses: fluidattacks/dast-action@0.1.0
        id: scan

      - name: Fail if vulnerabilities found
        if: steps.scan.outputs.vulnerabilities_found == 'true'
        run: exit 1

  secret-scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4

      - uses: fluidattacks/secret-scan-action@main
        id: scan
        with:
          scanner_mode: full

      - name: Upload results to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: ${{ steps.scan.outputs.sarif_file }}